-- First, add all the new columns to support the full Meta Ads data
ALTER TABLE public.meta_ads_campaigns
ADD COLUMN IF NOT EXISTS account_id text,
ADD COLUMN IF NOT EXISTS account_name text,
ADD COLUMN IF NOT EXISTS adset_id text,
ADD COLUMN IF NOT EXISTS ad_id text,
ADD COLUMN IF NOT EXISTS ad_name text,
ADD COLUMN IF NOT EXISTS campaign_status text,
ADD COLUMN IF NOT EXISTS adset_status text,
ADD COLUMN IF NOT EXISTS ad_status text,
ADD COLUMN IF NOT EXISTS objective text,
ADD COLUMN IF NOT EXISTS start_date date,
ADD COLUMN IF NOT EXISTS end_date date,
ADD COLUMN IF NOT EXISTS reach integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS frequency numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS results integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS purchases integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS leads integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_plays_100 integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_spend numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_starts integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_view_25 integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_view_50 integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_view_75 integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_view_100 integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS video_views integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpv numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpcv numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS vtr numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS thruplays integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpe numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS engagement_rate numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS engagements integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS landing_page_view integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpl numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS brand_suitability_blocked integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS brand_suitability_failed integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS impressions_verification integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS measurable_impressions integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS measurable_rate numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS tracked_ads integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS viewability_rate numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS viewability_rate_verification numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS viewability_impressions integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS platform text,
ADD COLUMN IF NOT EXISTS device text,
ADD COLUMN IF NOT EXISTS campaign_category text,
ADD COLUMN IF NOT EXISTS campaign_label text,
ADD COLUMN IF NOT EXISTS campaign_type text,
ADD COLUMN IF NOT EXISTS ad_set_label text,
ADD COLUMN IF NOT EXISTS ad_set_type text,
ADD COLUMN IF NOT EXISTS ad_category text,
ADD COLUMN IF NOT EXISTS ad_format text,
ADD COLUMN IF NOT EXISTS ad_type text,
ADD COLUMN IF NOT EXISTS age text,
ADD COLUMN IF NOT EXISTS gender text;